name: 'Terraform'

on:
  push:
    branches: ["terraform-aws"]
  pull_request:
    branches: ["terraform-aws"]

permissions:
  contents: read
    
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} 

      - name: Terraform Init
        run: terraform init

      # dont exit on error
      - name: Terraform Format
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -input=false

      # run only for push events
      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
